-- ==============================================
-- SUBJECT TEMPLATES
-- ==============================================
INSERT INTO public.subject_templates (id, name, code, internal_scored, internal_total, external_total, target_total, priority, focus) VALUES
('maths', 'Maths', 'GAMAT401', 31, 40, 60, 70, 'score_booster', 'Euler, Hamiltonian, Trees, algorithms, and PYQs'),
('ai', 'AI', 'PCCMT402', 29, 40, 60, 70, 'balanced', 'BFS, DFS, A*, minimax, alpha-beta, logic, and planning'),
('os', 'OS', 'PCCST403', 26, 40, 60, 70, 'make_or_break', 'Scheduling, deadlocks, memory, file systems + repeat twice'),
('dbms', 'DBMS', 'PBCMT404', 42, 50, 40, 70, 'free_marks', 'SQL, normalization, ER diagrams, and transactions'),
('adsa', 'ADSA', 'PECST495', 26, 30, 70, 70, 'score_booster', 'Sorting, graphs, complexity, and PYQs heavy'),
('economics', 'Economics', 'UCHUT346', 37, 50, 50, 70, 'balanced', 'Readable long answers, taxation, and writing practice')
ON CONFLICT (id) DO NOTHING;

-- ==============================================
-- MODULE TEMPLATES
-- ==============================================
INSERT INTO public.module_templates (id, subject_id, title, module_no) VALUES
-- Maths
('maths-m1', 'maths', 'Module 1', 1), ('maths-m2', 'maths', 'Module 2', 2), ('maths-m3', 'maths', 'Module 3', 3), ('maths-m4', 'maths', 'Module 4', 4),
-- AI
('ai-m1', 'ai', 'Module 1', 1), ('ai-m2', 'ai', 'Module 2', 2), ('ai-m3', 'ai', 'Module 3', 3), ('ai-m4', 'ai', 'Module 4', 4),
-- OS
('os-m1', 'os', 'Module 1', 1), ('os-m2', 'os', 'Module 2', 2), ('os-m3', 'os', 'Module 3', 3), ('os-m4', 'os', 'Module 4', 4),
-- DBMS
('dbms-m1', 'dbms', 'Module 1', 1), ('dbms-m2', 'dbms', 'Module 2', 2), ('dbms-m3', 'dbms', 'Module 3', 3), ('dbms-m4', 'dbms', 'Module 4', 4),
-- ADSA
('adsa-m1', 'adsa', 'Module 1', 1), ('adsa-m2', 'adsa', 'Module 2', 2), ('adsa-m3', 'adsa', 'Module 3', 3), ('adsa-m4', 'adsa', 'Module 4', 4),
-- Economics
('eco-m1', 'economics', 'Module 1', 1), ('eco-m2', 'economics', 'Module 2', 2), ('eco-m3', 'economics', 'Module 3', 3), ('eco-m4', 'economics', 'Module 4', 4)
ON CONFLICT (id) DO NOTHING;

-- ==============================================
-- TOPIC TEMPLATES
-- ==============================================
INSERT INTO public.topic_templates (id, subject_id, module_id, name, sort_order) VALUES
-- Maths M1
('m-1-1','maths','maths-m1','Basic definition of graphs',1),('m-1-2','maths','maths-m1','Applications of graphs',2),('m-1-3','maths','maths-m1','Finite and infinite graphs',3),('m-1-4','maths','maths-m1','Incidence and degree',4),('m-1-5','maths','maths-m1','Isolated vertex',5),('m-1-6','maths','maths-m1','Pendant vertex',6),('m-1-7','maths','maths-m1','Null graph',7),('m-1-8','maths','maths-m1','Isomorphism',8),('m-1-9','maths','maths-m1','Subgraphs',9),('m-1-10','maths','maths-m1','Walks',10),('m-1-11','maths','maths-m1','Paths',11),('m-1-12','maths','maths-m1','Circuits',12),('m-1-13','maths','maths-m1','Connected graphs',13),('m-1-14','maths','maths-m1','Disconnected graphs',14),('m-1-15','maths','maths-m1','Components',15),
-- Maths M2
('m-2-1','maths','maths-m2','Euler graphs',16),('m-2-2','maths','maths-m2','Operations on graphs',17),('m-2-3','maths','maths-m2','Hamiltonian paths',18),('m-2-4','maths','maths-m2','Hamiltonian circuits',19),('m-2-5','maths','maths-m2','Travelling Salesman Problem',20),('m-2-6','maths','maths-m2','Connectivity',21),('m-2-7','maths','maths-m2','Edge connectivity',22),('m-2-8','maths','maths-m2','Vertex connectivity',23),('m-2-9','maths','maths-m2','Directed graphs',24),('m-2-10','maths','maths-m2','Types of directed graphs',25),
-- Maths M3
('m-3-1','maths','maths-m3','Properties of trees',26),('m-3-2','maths','maths-m3','Pendant vertices',27),('m-3-3','maths','maths-m3','Distance and centres in a tree',28),('m-3-4','maths','maths-m3','Rooted trees',29),('m-3-5','maths','maths-m3','Binary trees',30),('m-3-6','maths','maths-m3','Counting trees',31),('m-3-7','maths','maths-m3','Spanning trees',32),('m-3-8','maths','maths-m3','Prim''s algorithm',33),('m-3-9','maths','maths-m3','Kruskal''s algorithm',34),('m-3-10','maths','maths-m3','Dijkstra''s shortest path algorithm',35),('m-3-11','maths','maths-m3','Floyd-Warshall shortest path algorithm',36),
-- Maths M4
('m-4-1','maths','maths-m4','Adjacency matrix',37),('m-4-2','maths','maths-m4','Incidence matrix',38),('m-4-3','maths','maths-m4','Circuit matrix',39),('m-4-4','maths','maths-m4','Path matrix',40),('m-4-5','maths','maths-m4','Coloring',41),('m-4-6','maths','maths-m4','Chromatic number',42),('m-4-7','maths','maths-m4','Chromatic polynomial',43),('m-4-8','maths','maths-m4','Greedy colouring algorithm',44),

-- AI M1
('ai-1-1','ai','ai-m1','Introduction to AI',1),('ai-1-2','ai','ai-m1','Foundations and history of AI',2),('ai-1-3','ai','ai-m1','Agents and environments',3),('ai-1-4','ai','ai-m1','Rationality',4),('ai-1-5','ai','ai-m1','Nature of environments',5),('ai-1-6','ai','ai-m1','Structure of agents',6),('ai-1-7','ai','ai-m1','Problem solving agents',7),('ai-1-8','ai','ai-m1','Well-defined problems and solutions',8),('ai-1-9','ai','ai-m1','Problem formulation',9),('ai-1-10','ai','ai-m1','Vacuum world',10),('ai-1-11','ai','ai-m1','8-puzzle',11),('ai-1-12','ai','ai-m1','8-queens',12),
-- AI M2
('ai-2-1','ai','ai-m2','Depth First Search',13),('ai-2-2','ai','ai-m2','Breadth First Search',14),('ai-2-3','ai','ai-m2','Iterative Deepening Search',15),('ai-2-4','ai','ai-m2','Heuristic functions',16),('ai-2-5','ai','ai-m2','Effect of heuristic accuracy',17),('ai-2-6','ai','ai-m2','Generate and test',18),('ai-2-7','ai','ai-m2','Greedy best first search',19),('ai-2-8','ai','ai-m2','A* algorithm',20),('ai-2-9','ai','ai-m2','Constraint satisfaction problems',21),('ai-2-10','ai','ai-m2','Cryptarithmetic problems',22),('ai-2-11','ai','ai-m2','Means-end analysis',23),('ai-2-12','ai','ai-m2','Simple hill climbing',24),('ai-2-13','ai','ai-m2','Simulated annealing',25),('ai-2-14','ai','ai-m2','Games',26),('ai-2-15','ai','ai-m2','Optimal decision in games',27),('ai-2-16','ai','ai-m2','Minimax algorithm',28),('ai-2-17','ai','ai-m2','Alpha-beta pruning',29),
-- AI M3
('ai-3-1','ai','ai-m3','Wumpus World',30),('ai-3-2','ai','ai-m3','Logic',31),('ai-3-3','ai','ai-m3','Propositional Logic',32),('ai-3-4','ai','ai-m3','Reasoning patterns in propositional logic',33),('ai-3-5','ai','ai-m3','First Order Logic',34),('ai-3-6','ai','ai-m3','Inference in first order logic',35),('ai-3-7','ai','ai-m3','Propositional vs first order inference',36),('ai-3-8','ai','ai-m3','Unification',37),('ai-3-9','ai','ai-m3','Forward chaining',38),('ai-3-10','ai','ai-m3','Backward chaining',39),
-- AI M4
('ai-4-1','ai','ai-m4','Classical planning',40),('ai-4-2','ai','ai-m4','Algorithms for classical planning',41),('ai-4-3','ai','ai-m4','Forward state-space search',42),('ai-4-4','ai','ai-m4','Backward search for planning',43),('ai-4-5','ai','ai-m4','Planning as Boolean satisfiability',44),('ai-4-6','ai','ai-m4','Heuristics for planning',45),('ai-4-7','ai','ai-m4','Domain-independent pruning',46),('ai-4-8','ai','ai-m4','State abstraction in planning',47),('ai-4-9','ai','ai-m4','Hierarchical planning',48),('ai-4-10','ai','ai-m4','High-level actions',49),('ai-4-11','ai','ai-m4','Searching for primitive solutions',50),('ai-4-12','ai','ai-m4','Searching for abstract solutions',51),('ai-4-13','ai','ai-m4','Planning and acting in nondeterministic domains',52),('ai-4-14','ai','ai-m4','Time, schedules, and resources',53),

-- OS M1
('os-1-1','os','os-m1','Introduction to operating systems',1),('os-1-2','os','os-m1','Operating system services',2),('os-1-3','os','os-m1','Overview of operating systems and kernels',3),('os-1-4','os','os-m1','Linux vs classic Unix kernels',4),('os-1-5','os','os-m1','Process creation',5),('os-1-6','os','os-m1','Process states',6),('os-1-7','os','os-m1','Process data structures',7),('os-1-8','os','os-m1','Process API',8),('os-1-9','os','os-m1','User and kernel modes',9),('os-1-10','os','os-m1','Context switching',10),('os-1-11','os','os-m1','System boot sequence',11),('os-1-12','os','os-m1','Linux kernel process management',12),('os-1-13','os','os-m1','Thread concept',13),('os-1-14','os','os-m1','Multithreading benefits',14),('os-1-15','os','os-m1','Multithreading models',15),('os-1-16','os','os-m1','Linux implementation of threads',16),('os-1-17','os','os-m1','Process scheduling concepts',17),('os-1-18','os','os-m1','Basic scheduling algorithms',18),('os-1-19','os','os-m1','Multilevel Feedback Queue',19),('os-1-20','os','os-m1','Linux Completely Fair Scheduler',20),('os-1-21','os','os-m1','Linux scheduling implementation',21),('os-1-22','os','os-m1','Preemption and context switching',22),
-- OS M2
('os-2-1','os','os-m2','Concurrency and synchronization basics',23),('os-2-2','os','os-m2','Locks',24),('os-2-3','os','os-m2','Spin locks',25),('os-2-4','os','os-m2','Test-and-set',26),('os-2-5','os','os-m2','Compare-and-swap',27),('os-2-6','os','os-m2','Queues and sleeping instead of spinning',28),('os-2-7','os','os-m2','Semaphores',29),('os-2-8','os','os-m2','Binary semaphores',30),('os-2-9','os','os-m2','Producer-consumer problem',31),('os-2-10','os','os-m2','Reader-writer locks',32),('os-2-11','os','os-m2','Linux kernel synchronization methods',33),('os-2-12','os','os-m2','Mutexes',34),('os-2-13','os','os-m2','Deadlock characterization',35),('os-2-14','os','os-m2','Deadlock prevention',36),('os-2-15','os','os-m2','Deadlock avoidance',37),('os-2-16','os','os-m2','Deadlock detection',38),('os-2-17','os','os-m2','Deadlock recovery',39),('os-2-18','os','os-m2','Dining philosophers problem',40),
-- OS M3
('os-3-1','os','os-m3','Address space',41),('os-3-2','os','os-m3','Memory API',42),('os-3-3','os','os-m3','Address translation',43),('os-3-4','os','os-m3','Dynamic relocation',44),('os-3-5','os','os-m3','Segmentation',45),('os-3-6','os','os-m3','Base and bounds',46),('os-3-7','os','os-m3','Address translation in segmentation',47),('os-3-8','os','os-m3','Support for sharing',48),('os-3-9','os','os-m3','Paging',49),('os-3-10','os','os-m3','Page tables',50),('os-3-11','os','os-m3','Hardware support for paging',51),('os-3-12','os','os-m3','TLBs',52),('os-3-13','os','os-m3','TLB hits and misses',53),('os-3-14','os','os-m3','TLB structure',54),('os-3-15','os','os-m3','Reducing page table size',55),('os-3-16','os','os-m3','Swap space',56),('os-3-17','os','os-m3','Page faults',57),('os-3-18','os','os-m3','Page replacement policies',58),('os-3-19','os','os-m3','Thrashing',59),
-- OS M4
('os-4-1','os','os-m4','Modern system architecture',60),('os-4-2','os','os-m4','Programmed I/O',61),('os-4-3','os','os-m4','Interrupts',62),('os-4-4','os','os-m4','DMA',63),('os-4-5','os','os-m4','Device interaction methods',64),('os-4-6','os','os-m4','Device driver',65),('os-4-7','os','os-m4','Hard disk geometry',66),('os-4-8','os','os-m4','Disk scheduling',67),('os-4-9','os','os-m4','Linux I/O schedulers',68),('os-4-10','os','os-m4','File descriptor',69),('os-4-11','os','os-m4','Sequential file access',70),('os-4-12','os','os-m4','Random file access',71),('os-4-13','os','os-m4','Removing files',72),('os-4-14','os','os-m4','Hard links',73),('os-4-15','os','os-m4','Symbolic links',74),('os-4-16','os','os-m4','Creating directories',75),('os-4-17','os','os-m4','Reading directories',76),('os-4-18','os','os-m4','Deleting directories',77),('os-4-19','os','os-m4','Permission bits',78),('os-4-20','os','os-m4','Access control lists',79),('os-4-21','os','os-m4','Mounting a file system',80),('os-4-22','os','os-m4','Inode',81),('os-4-23','os','os-m4','Multi-level index',82),('os-4-24','os','os-m4','VFS objects',83),('os-4-25','os','os-m4','Inode object',84),('os-4-26','os','os-m4','Inode operations',85),

-- DBMS M1
('dbms-1-1','dbms','dbms-m1','Database system concepts and architecture',1),('dbms-1-2','dbms','dbms-m1','Data models',2),('dbms-1-3','dbms','dbms-m1','Schemas and instances',3),('dbms-1-4','dbms','dbms-m1','Three-schema architecture',4),('dbms-1-5','dbms','dbms-m1','Data independence',5),('dbms-1-6','dbms','dbms-m1','Database languages and interfaces',6),('dbms-1-7','dbms','dbms-m1','Centralized DBMS architectures',7),('dbms-1-8','dbms','dbms-m1','Client/server architectures',8),('dbms-1-9','dbms','dbms-m1','Entity types',9),('dbms-1-10','dbms','dbms-m1','Entity sets',10),('dbms-1-11','dbms','dbms-m1','Attributes',11),('dbms-1-12','dbms','dbms-m1','Keys',12),('dbms-1-13','dbms','dbms-m1','Relationship types',13),('dbms-1-14','dbms','dbms-m1','Relationship sets',14),('dbms-1-15','dbms','dbms-m1','Roles',15),('dbms-1-16','dbms','dbms-m1','Structural constraints',16),('dbms-1-17','dbms','dbms-m1','Weak entity types',17),('dbms-1-18','dbms','dbms-m1','COMPANY database ER refinement',18),
-- DBMS M2
('dbms-2-1','dbms','dbms-m2','Relational data model',19),('dbms-2-2','dbms','dbms-m2','Relational database constraints',20),('dbms-2-3','dbms','dbms-m2','Relational algebra',21),('dbms-2-4','dbms','dbms-m2','Relational calculus',22),('dbms-2-5','dbms','dbms-m2','SQL',23),('dbms-2-6','dbms','dbms-m2','DDL',24),('dbms-2-7','dbms','dbms-m2','DML',25),('dbms-2-8','dbms','dbms-m2','Assertions',26),('dbms-2-9','dbms','dbms-m2','Triggers',27),('dbms-2-10','dbms','dbms-m2','Views',28),('dbms-2-11','dbms','dbms-m2','ER-to-relational mapping',29),
-- DBMS M3
('dbms-3-1','dbms','dbms-m3','Functional dependencies',30),('dbms-3-2','dbms','dbms-m3','Normalization',31),('dbms-3-3','dbms','dbms-m3','1NF',32),('dbms-3-4','dbms','dbms-m3','2NF',33),('dbms-3-5','dbms','dbms-m3','3NF',34),('dbms-3-6','dbms','dbms-m3','Transaction processing',35),('dbms-3-7','dbms','dbms-m3','Transaction problems and failures',36),('dbms-3-8','dbms','dbms-m3','Desirable properties of transactions',37),('dbms-3-9','dbms','dbms-m3','Recoverability',38),('dbms-3-10','dbms','dbms-m3','Serializability',39),('dbms-3-11','dbms','dbms-m3','Two-phase locking',40),('dbms-3-12','dbms','dbms-m3','Deferred update',41),('dbms-3-13','dbms','dbms-m3','Immediate update',42),('dbms-3-14','dbms','dbms-m3','Shadow paging',43),
-- DBMS M4
('dbms-4-1','dbms','dbms-m4','Types of NoSQL databases',44),('dbms-4-2','dbms','dbms-m4','CAP theorem',45),('dbms-4-3','dbms','dbms-m4','BASE properties',46),('dbms-4-4','dbms','dbms-m4','Use cases of NoSQL',47),('dbms-4-5','dbms','dbms-m4','Limitations of NoSQL',48),('dbms-4-6','dbms','dbms-m4','Key-value stores',49),('dbms-4-7','dbms','dbms-m4','Graph stores',50),('dbms-4-8','dbms','dbms-m4','Column family stores',51),('dbms-4-9','dbms','dbms-m4','Document stores',52),

-- ADSA M1
('adsa-1-1','adsa','adsa-m1','Arrays overview',1),('adsa-1-2','adsa','adsa-m1','Linked lists overview',2),('adsa-1-3','adsa','adsa-m1','Implementation of pointers and objects',3),('adsa-1-4','adsa','adsa-m1','Representing rooted trees',4),('adsa-1-5','adsa','adsa-m1','Hash tables',5),('adsa-1-6','adsa','adsa-m1','Hash functions',6),('adsa-1-7','adsa','adsa-m1','Cuckoo hashing',7),('adsa-1-8','adsa','adsa-m1','Bloom filters',8),('adsa-1-9','adsa','adsa-m1','Count-Min Sketch',9),('adsa-1-10','adsa','adsa-m1','Click stream processing using Bloom filters',10),('adsa-1-11','adsa','adsa-m1','Heavy hitters',11),('adsa-1-12','adsa','adsa-m1','Count-min structures',12),
-- ADSA M2
('adsa-2-1','adsa','adsa-m2','AVL trees review',13),('adsa-2-2','adsa','adsa-m2','Red-Black trees',14),('adsa-2-3','adsa','adsa-m2','Suffix trees',15),('adsa-2-4','adsa','adsa-m2','Suffix arrays',16),('adsa-2-5','adsa','adsa-m2','Segment trees',17),('adsa-2-6','adsa','adsa-m2','Binomial heap',18),('adsa-2-7','adsa','adsa-m2','Fibonacci heaps',19),('adsa-2-8','adsa','adsa-m2','Merkle trees',20),('adsa-2-9','adsa','adsa-m2','AutoComplete using tries',21),
-- ADSA M3
('adsa-3-1','adsa','adsa-m3','Quadtree',22),('adsa-3-2','adsa','adsa-m3','K-D trees',23),('adsa-3-3','adsa','adsa-m3','R-trees',24),('adsa-3-4','adsa','adsa-m3','Persistence',25),('adsa-3-5','adsa','adsa-m3','Retroactivity',26),('adsa-3-6','adsa','adsa-m3','Skip list',27),('adsa-3-7','adsa','adsa-m3','Tango trees',28),('adsa-3-8','adsa','adsa-m3','Approximate nearest neighbor search',29),('adsa-3-9','adsa','adsa-m3','Posting list intersection',30),
-- ADSA M4
('adsa-4-1','adsa','adsa-m4','Distributed hash tables',31),('adsa-4-2','adsa','adsa-m4','Consistent hashing',32),('adsa-4-3','adsa','adsa-m4','Distributed BST',33),('adsa-4-4','adsa','adsa-m4','Burrows-Wheeler Transform',34),('adsa-4-5','adsa','adsa-m4','Histogram',35),('adsa-4-6','adsa','adsa-m4','Wavelet trees',36),('adsa-4-7','adsa','adsa-m4','Cryptographic applications of hashing',37),

-- Economics M1
('eco-1-1','economics','eco-m1','Basic economic problems',1),('eco-1-2','economics','eco-m1','Production Possibility Curve',2),('eco-1-3','economics','eco-m1','Utility',3),('eco-1-4','economics','eco-m1','Law of diminishing marginal utility',4),('eco-1-5','economics','eco-m1','Law of demand',5),('eco-1-6','economics','eco-m1','Law of supply',6),('eco-1-7','economics','eco-m1','Elasticity',7),('eco-1-8','economics','eco-m1','Measurement of elasticity',8),('eco-1-9','economics','eco-m1','Applications of elasticity',9),('eco-1-10','economics','eco-m1','Equilibrium',10),('eco-1-11','economics','eco-m1','Changes in demand and supply and effects',11),('eco-1-12','economics','eco-m1','Production function',12),('eco-1-13','economics','eco-m1','Law of variable proportion',13),('eco-1-14','economics','eco-m1','Economies of scale',14),('eco-1-15','economics','eco-m1','Internal economies',15),('eco-1-16','economics','eco-m1','External economies',16),('eco-1-17','economics','eco-m1','Cobb-Douglas production function',17),
-- Economics M2
('eco-2-1','economics','eco-m2','Cost concepts',18),('eco-2-2','economics','eco-m2','Social cost',19),('eco-2-3','economics','eco-m2','Private cost',20),('eco-2-4','economics','eco-m2','Explicit cost',21),('eco-2-5','economics','eco-m2','Implicit cost',22),('eco-2-6','economics','eco-m2','Sunk cost',23),('eco-2-7','economics','eco-m2','Opportunity cost',24),('eco-2-8','economics','eco-m2','Short-run cost curves',25),('eco-2-9','economics','eco-m2','Revenue concepts',26),('eco-2-10','economics','eco-m2','Firms and their objectives',27),('eco-2-11','economics','eco-m2','Types of firms',28),('eco-2-12','economics','eco-m2','Markets',29),('eco-2-13','economics','eco-m2','Perfect competition',30),('eco-2-14','economics','eco-m2','Monopoly',31),('eco-2-15','economics','eco-m2','Monopolistic competition',32),('eco-2-16','economics','eco-m2','Oligopoly',33),('eco-2-17','economics','eco-m2','Equilibrium of a firm',34),
-- Economics M3
('eco-3-1','economics','eco-m3','Monetary system',35),('eco-3-2','economics','eco-m3','Money and its functions',36),('eco-3-3','economics','eco-m3','Central banking',37),('eco-3-4','economics','eco-m3','Inflation',38),('eco-3-5','economics','eco-m3','Causes and effects of inflation',39),('eco-3-6','economics','eco-m3','Measures to control inflation',40),('eco-3-7','economics','eco-m3','Monetary policy',41),('eco-3-8','economics','eco-m3','Fiscal policy',42),('eco-3-9','economics','eco-m3','Deflation',43),('eco-3-10','economics','eco-m3','Taxation',44),('eco-3-11','economics','eco-m3','Direct taxes',45),('eco-3-12','economics','eco-m3','Indirect taxes',46),('eco-3-13','economics','eco-m3','Merits and demerits of taxes',47),('eco-3-14','economics','eco-m3','GST',48),('eco-3-15','economics','eco-m3','National income',49),('eco-3-16','economics','eco-m3','Circular flow',50),('eco-3-17','economics','eco-m3','Methods of estimation',51),('eco-3-18','economics','eco-m3','Difficulties in estimation',52),('eco-3-19','economics','eco-m3','Stock market',53),('eco-3-20','economics','eco-m3','Functions of stock market',54),('eco-3-21','economics','eco-m3','Problems in Indian stock market',55),('eco-3-22','economics','eco-m3','Demat account',56),('eco-3-23','economics','eco-m3','Trading account',57),('eco-3-24','economics','eco-m3','SENSEX',58),('eco-3-25','economics','eco-m3','NIFTY',59),
-- Economics M4
('eco-4-1','economics','eco-m4','Value analysis',60),('eco-4-2','economics','eco-m4','Value engineering',61),('eco-4-3','economics','eco-m4','Cost value',62),('eco-4-4','economics','eco-m4','Exchange value',63),('eco-4-5','economics','eco-m4','Use value',64),('eco-4-6','economics','eco-m4','Esteem value',65),('eco-4-7','economics','eco-m4','Aims of value engineering',66),('eco-4-8','economics','eco-m4','Advantages of value engineering',67),('eco-4-9','economics','eco-m4','Application areas of value engineering',68),('eco-4-10','economics','eco-m4','Value engineering procedure',69),('eco-4-11','economics','eco-m4','Break-even analysis',70),('eco-4-12','economics','eco-m4','Cost-benefit analysis',71),('eco-4-13','economics','eco-m4','Capital budgeting',72),('eco-4-14','economics','eco-m4','Process planning',73)
ON CONFLICT (id) DO NOTHING;
