-- ==============================================
-- SUBJECT TEMPLATES
-- ==============================================
INSERT INTO public.subject_templates (id, name, code, internal_scored, internal_total, external_total, target_total, priority, focus, exam_date, sort_order) VALUES
('maths', 'Maths', 'GAMAT401', 31, 40, 60, 70, 'score_booster', 'Euler, Hamiltonian, Trees, algorithms, and PYQs', '2026-04-27', 1),
('ai', 'AI', 'PCCMT402', 29, 40, 60, 70, 'balanced', 'BFS, DFS, A*, minimax, alpha-beta, logic, and planning', '2026-04-29', 2),
('os', 'OS', 'PCCST403', 26, 40, 60, 70, 'make_or_break', 'Scheduling, deadlocks, memory, file systems + repeat twice', '2026-05-04', 3),
('dbms', 'DBMS', 'PBCMT404', 42, 50, 40, 70, 'free_marks', 'SQL, normalization, ER diagrams, and transactions', '2026-05-07', 4),
('adsa', 'ADSA', 'PECST495', 26, 30, 70, 70, 'score_booster', 'Sorting, graphs, complexity, and PYQs heavy', '2026-05-11', 5),
('economics', 'Economics', 'UCHUT346', 37, 50, 50, 70, 'balanced', 'Readable long answers, taxation, and writing practice', '2026-05-14', 6),
('coa', 'COA', 'PCCST405', 28, 50, 50, 70, 'make_or_break', 'Microarchitecture, Pipelining, Caches, and DMA', NULL, 7),
('soft', 'Soft Computing', 'PECST496', 32, 50, 50, 70, 'balanced', 'Neural Networks, Fuzzy Logic, Genetic Algorithms', NULL, 8)
ON CONFLICT (id) DO UPDATE SET focus = EXCLUDED.focus, exam_date = EXCLUDED.exam_date, sort_order = EXCLUDED.sort_order;

-- ==============================================
-- MODULE TEMPLATES
-- ==============================================
INSERT INTO public.module_templates (id, subject_id, title, module_no, sort_order) VALUES
('maths-m1', 'maths', 'Module 1', 1, 1),
('maths-m2', 'maths', 'Module 2', 2, 2),
('maths-m3', 'maths', 'Module 3', 3, 3),
('maths-m4', 'maths', 'Module 4', 4, 4),
('ai-m1', 'ai', 'Module 1', 1, 1),
('ai-m2', 'ai', 'Module 2', 2, 2),
('ai-m3', 'ai', 'Module 3', 3, 3),
('ai-m4', 'ai', 'Module 4', 4, 4),
('os-m1', 'os', 'Module 1', 1, 1),
('os-m2', 'os', 'Module 2', 2, 2),
('os-m3', 'os', 'Module 3', 3, 3),
('os-m4', 'os', 'Module 4', 4, 4),
('dbms-m1', 'dbms', 'Module 1', 1, 1),
('dbms-m2', 'dbms', 'Module 2', 2, 2),
('dbms-m3', 'dbms', 'Module 3', 3, 3),
('dbms-m4', 'dbms', 'Module 4', 4, 4),
('adsa-m1', 'adsa', 'Module 1', 1, 1),
('adsa-m2', 'adsa', 'Module 2', 2, 2),
('adsa-m3', 'adsa', 'Module 3', 3, 3),
('adsa-m4', 'adsa', 'Module 4', 4, 4),
('eco-m1', 'economics', 'Module 1', 1, 1),
('eco-m2', 'economics', 'Module 2', 2, 2),
('eco-m3', 'economics', 'Module 3', 3, 3),
('eco-m4', 'economics', 'Module 4', 4, 4),
('coa-m1', 'coa', 'Module 1', 1, 1),
('coa-m2', 'coa', 'Module 2', 2, 2),
('coa-m3', 'coa', 'Module 3', 3, 3),
('coa-m4', 'coa', 'Module 4', 4, 4),
('soft-m1', 'soft', 'Module 1', 1, 1),
('soft-m2', 'soft', 'Module 2', 2, 2),
('soft-m3', 'soft', 'Module 3', 3, 3),
('soft-m4', 'soft', 'Module 4', 4, 4)
ON CONFLICT (id) DO NOTHING;

-- ==============================================
-- TOPIC TEMPLATES
-- ==============================================
INSERT INTO public.topic_templates (id, subject_id, module_id, name, sort_order) VALUES
-- MATHS
('m-1-1','maths','maths-m1','Introduction to Graphs - Basic definition',1),
('m-1-2','maths','maths-m1','Application of graphs',2),
('m-1-3','maths','maths-m1','finite and infinite graphs',3),
('m-1-4','maths','maths-m1','Incidence and Degree',4),
('m-1-5','maths','maths-m1','Isolated vertex',5),
('m-1-6','maths','maths-m1','Pendant vertex and Null graph',6),
('m-1-7','maths','maths-m1','Isomorphism',7),
('m-1-8','maths','maths-m1','Sub graphs',8),
('m-1-9','maths','maths-m1','Walks',9),
('m-1-10','maths','maths-m1','Paths and circuits',10),
('m-1-11','maths','maths-m1','Connected graphs',11),
('m-1-12','maths','maths-m1','Disconnected graphs and components',12),
('m-2-1','maths','maths-m2','Euler graphs',13),
('m-2-2','maths','maths-m2','Operations on Graphs',14),
('m-2-3','maths','maths-m2','Hamiltonian paths and circuits',15),
('m-2-4','maths','maths-m2','Travelling Salesman Problem',16),
('m-2-5','maths','maths-m2','Directed graphs',17),
('m-2-6','maths','maths-m2','Types of directed graphs',18),
('m-3-1','maths','maths-m3','Trees- properties',19),
('m-3-2','maths','maths-m3','Pendant vertices',20),
('m-3-3','maths','maths-m3','Distance and centres in a tree',21),
('m-3-4','maths','maths-m3','Rooted and binary trees',22),
('m-3-5','maths','maths-m3','Counting trees',23),
('m-3-6','maths','maths-m3','Spanning trees',24),
('m-3-7','maths','maths-m3','Prim''''s algorithm and Kruskal''''s algorithm',25),
('m-3-8','maths','maths-m3','Dijkstra''''s shortest path algorithm',26),
('m-3-9','maths','maths-m3','Floyd-Warshall shortest path algorithm',27),
('m-4-1','maths','maths-m4','Cut Set and its properties Connectivity',28),
('m-4-2','maths','maths-m4','Edge connectivity',29),
('m-4-3','maths','maths-m4','Vertex connectivity',30),
('m-4-4','maths','maths-m4','Matrix representation of graphs- Adjacency matrix',31),
('m-4-5','maths','maths-m4','Incidence Matrix',32),
('m-4-6','maths','maths-m4','Circuit Matrix',33),
('m-4-7','maths','maths-m4','Path Matrix',34),
-- AI
('ai-1-1','ai','ai-m1','Introduction to Artificial Intelligence',1),
('ai-1-2','ai','ai-m1','Foundation and history of AI',2),
('ai-1-3','ai','ai-m1','Agents and Environments',3),
('ai-1-4','ai','ai-m1','The concept of rationality',4),
('ai-1-5','ai','ai-m1','The nature of environments',5),
('ai-1-6','ai','ai-m1','Structure of agents',6),
('ai-1-7','ai','ai-m1','Problem solving Agents',7),
('ai-1-8','ai','ai-m1','Well-defined problems and solutions',8),
('ai-1-9','ai','ai-m1','Formulating problems',9),
('ai-1-10','ai','ai-m1','Example problems- vacuum world, 8-puzzle, 8-queens',10),
('ai-2-1','ai','ai-m2','Blind Search strategies',11),
('ai-2-2','ai','ai-m2','Depth First Search',12),
('ai-2-3','ai','ai-m2','Breadth First Search',13),
('ai-2-4','ai','ai-m2','Iterative Deepening Search',14),
('ai-2-5','ai','ai-m2','Heuristic Search strategies',15),
('ai-2-6','ai','ai-m2','Heuristic functions',16),
('ai-2-7','ai','ai-m2','The effect of heuristic accuracy on performance',17),
('ai-2-8','ai','ai-m2','Generate and test',18),
('ai-2-9','ai','ai-m2','Greedy best first search',19),
('ai-2-10','ai','ai-m2','A* algorithm',20),
('ai-2-11','ai','ai-m2','Constraint satisfaction problems',21),
('ai-2-12','ai','ai-m2','Cryptarithmetic problems',22),
('ai-2-13','ai','ai-m2','Means-end analysis',23),
('ai-2-14','ai','ai-m2','Local search strategies - Simple Hill Climbing',24),
('ai-2-15','ai','ai-m2','Simulated Annealing',25),
('ai-2-16','ai','ai-m2','Adversarial search - Games',26),
('ai-2-17','ai','ai-m2','Optimal Decision in games',27),
('ai-2-18','ai','ai-m2','The minimax algorithm',28),
('ai-2-19','ai','ai-m2','Alpha–beta pruning',29),
('ai-3-1','ai','ai-m3','The Wumpus World',30),
('ai-3-2','ai','ai-m3','Logic',31),
('ai-3-3','ai','ai-m3','Propositional Logic',32),
('ai-3-4','ai','ai-m3','Reasoning Patterns in Propositional Logic',33),
('ai-3-5','ai','ai-m3','First order logic',34),
('ai-3-6','ai','ai-m3','Inference in first order logic',35),
('ai-3-7','ai','ai-m3','propositional vs. first order inference',36),
('ai-3-8','ai','ai-m3','unification & lifts',37),
('ai-3-9','ai','ai-m3','forward chaining',38),
('ai-3-10','ai','ai-m3','Backward chaining',39),
('ai-4-1','ai','ai-m4','Classical planning',40),
('ai-4-2','ai','ai-m4','Algorithms for Classical Planning',41),
('ai-4-3','ai','ai-m4','Forward state-space search for planning',42),
('ai-4-4','ai','ai-m4','Backward search for planning',43),
('ai-4-5','ai','ai-m4','Planning as Boolean satisfiability',44),
('ai-4-6','ai','ai-m4','Heuristics for Planning',45),
('ai-4-7','ai','ai-m4','Domain-independent pruning',46),
('ai-4-8','ai','ai-m4','State abstraction in planning',47),
('ai-4-9','ai','ai-m4','Hierarchical Planning',48),
('ai-4-10','ai','ai-m4','High-level actions',49),
('ai-4-11','ai','ai-m4','Searching for primitive solutions',50),
('ai-4-12','ai','ai-m4','Searching for abstract solutions',51),
('ai-4-13','ai','ai-m4','Planning and Acting in Nondeterministic Domains',52),
('ai-4-14','ai','ai-m4','Time, Schedules, and Resources',53),
-- OS
('os-1-1','os','os-m1','Introduction to Operating Systems',1),
('os-1-2','os','os-m1','Operating System Services',2),
('os-1-3','os','os-m1','Overview of Operating Systems and Kernels',3),
('os-1-4','os','os-m1','Linux Versus Classic Unix Kernels',4),
('os-1-5','os','os-m1','Process concepts: Process Creation, Process States, Data Structures, Process API',5),
('os-1-6','os','os-m1','Sharing processor among processes - user and kernel modes, context switching',6),
('os-1-7','os','os-m1','System boot sequence',7),
('os-1-8','os','os-m1','Case study: Linux kernel process management',8),
('os-1-9','os','os-m1','Threads and Concurrency: Concept of a thread, Multithreading benefits, Multithreading models',9),
('os-1-10','os','os-m1','Case study: The Linux Implementation of Threads',10),
('os-1-11','os','os-m1','Process scheduling: Concepts and basic algorithms',11),
('os-1-12','os','os-m1','The Multilevel Feedback Queue: Basic Rules',12),
('os-1-13','os','os-m1','Case study: The Linux Completely Fair Scheduler (CFS)',13),
('os-1-14','os','os-m1','The Linux Scheduling Implementation',14),
('os-1-15','os','os-m1','Preemption and Context Switching',15),
('os-2-1','os','os-m2','Concurrency and Synchronization - Basic principles',16),
('os-2-2','os','os-m2','Mechanisms - Locks: The Basic Idea',17),
('os-2-3','os','os-m2','Building Spin Locks with Test-And-Set',18),
('os-2-4','os','os-m2','Compare and Swap',19),
('os-2-5','os','os-m2','Using Queues: Sleeping Instead Of Spinning',20),
('os-2-6','os','os-m2','Semaphores - Definition, Binary Semaphores',21),
('os-2-7','os','os-m2','The Producer/Consumer (Bounded Buffer) Problem and its solution using semaphores',22),
('os-2-8','os','os-m2','Reader-Writer Locks',23),
('os-2-9','os','os-m2','Case study: Linux Kernel Synchronization Methods - Spin Locks, Semaphores, Mutexes',24),
('os-2-10','os','os-m2','Concurrency: Deadlock and Starvation - Deadlock Characterization',25),
('os-2-11','os','os-m2','Deadlock Prevention and Avoidance',26),
('os-2-12','os','os-m2','Deadlock Detection and recovery',27),
('os-2-13','os','os-m2','Dining Philosophers Problem and its solution',28),
('os-3-1','os','os-m3','Memory management - Address Space, Memory API',29),
('os-3-2','os','os-m3','Address Translation - An Example',30),
('os-3-3','os','os-m3','Dynamic (Hardware-based) Relocation',31),
('os-3-4','os','os-m3','Segmentation: Generalized Base/Bounds',32),
('os-3-5','os','os-m3','Address translation in segmentation',33),
('os-3-6','os','os-m3','Support for Sharing',34),
('os-3-7','os','os-m3','Virtual memory - Paging: Introduction, page tables and hardware support',35),
('os-3-8','os','os-m3','TLBs, Example: Accessing An Array',36),
('os-3-9','os','os-m3','TLB hits and misses, Handling TLB misses, TLB structure',37),
('os-3-10','os','os-m3','Reducing the page table size',38),
('os-3-11','os','os-m3','Going beyond physical memory - Swap space',39),
('os-3-12','os','os-m3','page fault and its control flow',40),
('os-3-13','os','os-m3','page replacement policies',41),
('os-3-14','os','os-m3','Thrashing',42),
('os-4-1','os','os-m4','I/O system: Modern System architecture',43),
('os-4-2','os','os-m4','Programmed I/O, Interrupts, DMA',44),
('os-4-3','os','os-m4','Device interaction methods, The Device Driver',45),
('os-4-4','os','os-m4','Hard disk: Geometry',46),
('os-4-5','os','os-m4','disk scheduling',47),
('os-4-6','os','os-m4','Case study: Linux I/O schedulers - Elevator, Complete Fair Queuing',48),
('os-4-7','os','os-m4','Files and Directories: The File System Interface - File descriptor, reading and writing files (sequential and random access)',49),
('os-4-8','os','os-m4','Removing files - Hard links and Symbolic links',50),
('os-4-9','os','os-m4','Creating, reading and deleting directories',51),
('os-4-10','os','os-m4','Permission bits and Access Control Lists',52),
('os-4-11','os','os-m4','Mounting a file system',53),
('os-4-12','os','os-m4','File Organization: The Inode, The Multi-Level Index',54),
('os-4-13','os','os-m4','Case study: VFS Objects and Their Data Structures - The Inode Object, Inode Operations',55),
-- DBMS
('dbms-1-1','dbms','dbms-m1','Introduction to Databases',1),
('dbms-1-2','dbms','dbms-m1','Database System Concepts and Architecture - Data Models, Schemas and Instances',2),
('dbms-1-3','dbms','dbms-m1','Three-Schema Architecture and Data Independence',3),
('dbms-1-4','dbms','dbms-m1','Database Languages and Interfaces',4),
('dbms-1-5','dbms','dbms-m1','Centralized and Client/Server Architectures for DBMSs',5),
('dbms-1-6','dbms','dbms-m1','Conceptual Data Modelling and Database Design',6),
('dbms-1-7','dbms','dbms-m1','Data Modelling Using the Entity-Relationship Model - Entity Types, Entity Sets, Attributes, and Keys',7),
('dbms-1-8','dbms','dbms-m1','Relationship Types, Relationship Sets, Roles, and Structural Constraints',8),
('dbms-1-9','dbms','dbms-m1','Weak Entity Types',9),
('dbms-1-10','dbms','dbms-m1','Refining the ER Design for the COMPANY Database',10),
('dbms-2-1','dbms','dbms-m2','The Relational Data Model and SQL',11),
('dbms-2-2','dbms','dbms-m2','The Relational Data Model and Relational Database Constraints',12),
('dbms-2-3','dbms','dbms-m2','Relational Algebra and Relational Calculus',13),
('dbms-2-4','dbms','dbms-m2','Structured Query Language (SQL)',14),
('dbms-2-5','dbms','dbms-m2','Data Definition Language, Data Manipulation Language, Assertions, Triggers, views',15),
('dbms-2-6','dbms','dbms-m2','Relational Database Design Using ER-to-Relational Mapping',16),
('dbms-3-1','dbms','dbms-m3','Database Design Theory and Normalization',17),
('dbms-3-2','dbms','dbms-m3','Functional Dependencies- Basic definition',18),
('dbms-3-3','dbms','dbms-m3','Normalization- First, Second and Third normal forms',19),
('dbms-3-4','dbms','dbms-m3','Transaction Management',20),
('dbms-3-5','dbms','dbms-m3','Transaction Processing - Introduction, problems and failures in transaction',21),
('dbms-3-6','dbms','dbms-m3','Desirable properties of transaction',22),
('dbms-3-7','dbms','dbms-m3','Characterizing schedules based on recoverability and serializability',23),
('dbms-3-8','dbms','dbms-m3','Concurrency Control with Two-Phase Locking Techniques',24),
('dbms-3-9','dbms','dbms-m3','Database Recovery management: Deferred update-immediate update- shadow paging',25),
('dbms-4-1','dbms','dbms-m4','Introduction to NoSQL Concepts',26),
('dbms-4-2','dbms','dbms-m4','Types of NoSQL databases',27),
('dbms-4-3','dbms','dbms-m4','CAP Theorem',28),
('dbms-4-4','dbms','dbms-m4','BASE properties',29),
('dbms-4-5','dbms','dbms-m4','Use Cases and limitations of NoSQL',30),
('dbms-4-6','dbms','dbms-m4','SQL Architectural Patterns',31),
('dbms-4-7','dbms','dbms-m4','Key value Stores',32),
('dbms-4-8','dbms','dbms-m4','Graph Stores',33),
('dbms-4-9','dbms','dbms-m4','Column Family stores',34),
('dbms-4-10','dbms','dbms-m4','Document Stores',35),
-- ADSA
('adsa-1-1','adsa','adsa-m1','Foundational Data Structures- Overview of Arrays and Linked Lists',1),
('adsa-1-2','adsa','adsa-m1','implementation of pointers and objects',2),
('adsa-1-3','adsa','adsa-m1','Representing rooted trees',3),
('adsa-1-4','adsa','adsa-m1','Hashing - Hash Tables, Hash functions, Cuckoo Hashing',4),
('adsa-1-5','adsa','adsa-m1','Bloom Filters - Count-Min Sketch',5),
('adsa-1-6','adsa','adsa-m1','Applications to Networks - Click Stream Processing using Bloom Filters',6),
('adsa-1-7','adsa','adsa-m1','Applications to Data Science - Heavy Hitters and count-min structures',7),
('adsa-2-1','adsa','adsa-m2','Advanced Tree Data Structures',8),
('adsa-2-2','adsa','adsa-m2','Balanced Trees - AVL Trees (review)',9),
('adsa-2-3','adsa','adsa-m2','Red-Black Trees',10),
('adsa-2-4','adsa','adsa-m2','Suffix Trees and Arrays',11),
('adsa-2-5','adsa','adsa-m2','Segment Trees',12),
('adsa-2-6','adsa','adsa-m2','Heaps and Related Structures – Binomial heap, Fibonacci Heaps',13),
('adsa-2-7','adsa','adsa-m2','Merkle Trees',14),
('adsa-2-8','adsa','adsa-m2','Applications to information Retrieval and WWW - AutoComplete using Tries',15),
('adsa-3-1','adsa','adsa-m3','Specialized Data Structures',16),
('adsa-3-2','adsa','adsa-m3','Spatial Data Structures – Quadtree, K-D Trees (k-dimensional tree)',17),
('adsa-3-3','adsa','adsa-m3','R-trees',18),
('adsa-3-4','adsa','adsa-m3','Temporal Data Structures- Persistence, Retroactivity',19),
('adsa-3-5','adsa','adsa-m3','Search and Optimization Trees – Skip List, Tango Trees',20),
('adsa-3-6','adsa','adsa-m3','Applications to Data Science - Approximate nearest neighbor search',21),
('adsa-3-7','adsa','adsa-m3','Applications to information Retrieval and WWW, Posting List intersection',22),
('adsa-4-1','adsa','adsa-m4','Data Structure applications',23),
('adsa-4-2','adsa','adsa-m4','Distributed and Parallel Data Structures - Distributed Hash Tables (DHTs)',24),
('adsa-4-3','adsa','adsa-m4','Consistent Hashing',25),
('adsa-4-4','adsa','adsa-m4','Distributed BST',26),
('adsa-4-5','adsa','adsa-m4','Data Compression and Transformations - Burrows-Wheeler Transform',27),
('adsa-4-6','adsa','adsa-m4','Histogram',28),
('adsa-4-7','adsa','adsa-m4','Wavelet Trees',29),
('adsa-4-8','adsa','adsa-m4','Cryptographic Applications – Hashing',30),
-- ECONOMICS
('eco-1-1','economics','eco-m1','Basic economic problems',1),
('eco-1-2','economics','eco-m1','Production Possibility Curve',2),
('eco-1-3','economics','eco-m1','Utility',3),
('eco-1-4','economics','eco-m1','Law of diminishing marginal utility',4),
('eco-1-5','economics','eco-m1','Demand: Factors determining demand',5),
('eco-1-6','economics','eco-m1','Law of Demand',6),
('eco-1-7','economics','eco-m1','Demand curve',7),
('eco-1-8','economics','eco-m1','Price elasticity of demand- measurement of price elasticity and its applications',8),
('eco-1-9','economics','eco-m1','Supply: factors determining supply',9),
('eco-1-10','economics','eco-m1','Law of supply',10),
('eco-1-11','economics','eco-m1','Supply curve',11),
('eco-1-12','economics','eco-m1','Equilibrium price determination',12),
('eco-1-13','economics','eco-m1','Changes in demand and supply and its effects on equilibrium price and quantity',13),
('eco-1-14','economics','eco-m1','Production: Production function',14),
('eco-1-15','economics','eco-m1','Law of variable proportion',15),
('eco-1-16','economics','eco-m1','Returns to scale',16),
('eco-1-17','economics','eco-m1','Cobb-Douglas Production Function',17),
('eco-2-1','economics','eco-m2','Cost concepts',18),
('eco-2-2','economics','eco-m2','Private cost and social cost',19),
('eco-2-3','economics','eco-m2','Sunk cost',20),
('eco-2-4','economics','eco-m2','Opportunity cost',21),
('eco-2-5','economics','eco-m2','Explicit and implicit cost',22),
('eco-2-6','economics','eco-m2','Short run cost curves',23),
('eco-2-7','economics','eco-m2','Long run average cost curve',24),
('eco-2-8','economics','eco-m2','Revenue concepts',25),
('eco-2-9','economics','eco-m2','Break-even point',26),
('eco-2-10','economics','eco-m2','Market: Perfect Competition',27),
('eco-2-11','economics','eco-m2','Monopoly',28),
('eco-2-12','economics','eco-m2','Monopolistic Competition (features and equilibrium of a firm)',29),
('eco-2-13','economics','eco-m2','Oligopoly – Features',30),
('eco-2-14','economics','eco-m2','Kinked demand model',31),
('eco-3-1','economics','eco-m3','National income: Concepts (GDP, GNP and NNP)',32),
('eco-3-2','economics','eco-m3','Final goods and Intermediate goods',33),
('eco-3-3','economics','eco-m3','Methods of Estimation',34),
('eco-3-4','economics','eco-m3','output method',35),
('eco-3-5','economics','eco-m3','expenditure method',36),
('eco-3-6','economics','eco-m3','Difficulties in the measurement of national income',37),
('eco-3-7','economics','eco-m3','Inflation: Causes and Effects',38),
('eco-3-8','economics','eco-m3','Measures to Control Inflation',39),
('eco-3-9','economics','eco-m3','Monetary and Fiscal policies',40),
('eco-3-10','economics','eco-m3','Repo and reverse repo rate',41),
('eco-4-1','economics','eco-m4','Value Analysis and value Engineering',42),
('eco-4-2','economics','eco-m4','Cost Value, Exchange Value, Use Value, Esteem Value',43),
('eco-4-3','economics','eco-m4','Aims, Advantages and Application areas of Value Engineering',44),
('eco-4-4','economics','eco-m4','Value Engineering Procedure',45),
('eco-4-5','economics','eco-m4','Capital Budgeting: Time value of money',46),
('eco-4-6','economics','eco-m4','Net Present Value Method',47),
('eco-4-7','economics','eco-m4','Benefit Cost Ratio',48),
('eco-4-8','economics','eco-m4','Internal Rate of Return',49),
('eco-4-9','economics','eco-m4','Payback',50),
('eco-4-10','economics','eco-m4','Accounting Rate of Return',51),
-- COA
('coa-1-1','coa','coa-m1','Functional units and basic concepts',1),
('coa-1-2','coa','coa-m1','Memory map and Endianness',2),
('coa-1-3','coa','coa-m1','CISC vs RISC architectures',3),
('coa-1-4','coa','coa-m1','Programming concepts and flow',4),
('coa-1-5','coa','coa-m1','Instruction execution cycle',5),
('coa-1-6','coa','coa-m1','Machine language and addressing modes',6),
('coa-2-1','coa','coa-m2','Microarchitecture Introduction',7),
('coa-2-2','coa','coa-m2','Single-Cycle Processor Datapath',8),
('coa-2-3','coa','coa-m2','Single Cycle Control',9),
('coa-2-4','coa','coa-m2','Pipelined Data Path',10),
('coa-2-5','coa','coa-m2','Data and Control Hazards',11),
('coa-2-6','coa','coa-m2','Performance Analysis',12),
('coa-3-1','coa','coa-m3','Memory Systems and performance',13),
('coa-3-2','coa','coa-m3','Caches: mapping and replacement',14),
('coa-3-3','coa','coa-m3','Multiple-Level Caches',15),
('coa-3-4','coa','coa-m3','Virtual Memory and Address Translation',16),
('coa-3-5','coa','coa-m3','Translation Lookaside Buffer (TLB)',17),
('coa-4-1','coa','coa-m4','Input / Output External Devices',18),
('coa-4-2','coa','coa-m4','Programmed I/O and Interrupt Driven I/O',19),
('coa-4-3','coa','coa-m4','Direct Memory Access (DMA)',20),
('coa-4-4','coa','coa-m4','Embedded I/O Systems',21),
('coa-4-5','coa','coa-m4','Serial I/O and Peripherals',22),
-- SOFT
('soft-1-1','soft','soft-m1','Difference between Hard & Soft Computing',1),
('soft-1-2','soft','soft-m1','Artificial vs Biological Neurons',2),
('soft-1-3','soft','soft-m1','Activation Functions and Learning',3),
('soft-1-4','soft','soft-m1','McCulloch and Pitts Neuron',4),
('soft-1-5','soft','soft-m1','Perceptron Networks Training',5),
('soft-1-6','soft','soft-m1','Adaptive Linear Neuron',6),
('soft-2-1','soft','soft-m2','Fuzzy sets and Properties',7),
('soft-2-2','soft','soft-m2','Fuzzy membership functions',8),
('soft-2-3','soft','soft-m2','Linguistic variables and hedges',9),
('soft-2-4','soft','soft-m2','Fuzzy If-Then Rules',10),
('soft-2-5','soft','soft-m2','Fuzzification and Lamda cuts',11),
('soft-2-6','soft','soft-m2','Mamdani and Sugeno Inference',12),
('soft-3-1','soft','soft-m3','Evolutionary Computing Terminologies',13),
('soft-3-2','soft','soft-m3','Concepts of genetic algorithm',14),
('soft-3-3','soft','soft-m3','Coding in genetic algorithm',15),
('soft-3-4','soft','soft-m3','Selection, cross over, mutation',16),
('soft-3-5','soft','soft-m3','Stopping condition',17),
('soft-4-1','soft','soft-m4','Multi-objective optimization problem',18),
('soft-4-2','soft','soft-m4','Dominance and pareto-optimality',19),
('soft-4-3','soft','soft-m4','Biological Self-Organization',20),
('soft-4-4','soft','soft-m4','Particle Swarm Optimization',21),
('soft-4-5','soft','soft-m4','Ant Colony Optimization',22)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;